### ISSUE TITLE
Channel.close() doesn't trigger reconnect

### ISSUE THREAD

**Issue by MartinWickman** [benbria/node-amqp-connection-manager#99]
If my consumer function calls  `channel.close()` (on the channelWrapper that is) everything stops, ie no reconnect happens.

Or more general, what is supposed to happen if the channel closes for whatever reason?

**Comment by jwalton** [comment]
If you explicitly call "close" you're saying "I'm done with this channel", so we close the channel and stop trying to reconnect it.  (If we didn't do this, there'd be no easy way to cleanly terminate.)

If the underlying channel closes (because e.g. RabbitMQ restarts or there's a network problem) then we'll automatically reconnect the channel.

**Comment by MartinWickman** [comment]
Yes, you're correct. There is really no need to explicitly call close on the channel.
